fix for issue 1020
openBackhaul/ApplicationPattern pull request #1021
Opened 2024-09-30 05:47 UTC by ManasaBM1

2024-09-30 05:48 UTC, ManasaBM1 commented
Reviewers is @PrathibaJee

2024-10-03 04:53 UTC, IswaryaaS requested changes

2024-10-03 04:53 UTC, IswaryaaS commented on server/basicServices/basicServices/BasicServicesService.js
> +if((currentApplicationName == futureApplicationName || currentApplicationName !== futureApplicationName) && currentReleaseNumber !== futureReleaseNumber){
this condition **(currentApplicationName == futureApplicationName || currentApplicationName !== futureApplicationName)** will return true for all cases, hence it shall be reformed.

2024-10-03 07:03 UTC, IswaryaaS requested changes

2024-10-03 09:01 UTC, IswaryaaS requested changes

2024-10-03 09:01 UTC, IswaryaaS commented on server/basicServices/basicServices/BasicServicesService.js
> +    if (httpClientUuidOfCurrentApplication !== httpClientUuidOfFutureApplication) {
kindly also include a check to make sure httpClientUuidOfCurrentApplication is present ..

2024-10-03 09:30 UTC, IswaryaaS approved these changes

2024-10-03 09:30 UTC, merged