issue-259 : update implementation doc for Basic Services
openBackhaul/ApplicationPattern pull request #618
Opened 2023-03-27 07:55 UTC by DanaSunal

2023-03-28 07:26 UTC, DanaSunal commented
Reviewer is @IswaryaaS

2023-04-03 08:39 UTC, IswaryaaS reviewed
Assigning the PR to @vanithavalluripalli9  as the changes are more related to server side code

2023-04-10 16:50 UTC, vanithavalluripalli9 requested changes

2023-04-10 16:50 UTC, vanithavalluripalli9 commented on doc/ImplementingApplications/Steps2IntegrateBasicServices/Steps2IntegrateBasicServices.md
> +  A formulated response header will consists of the xCorrelator sent in the request , start-time and the lifecycle-state of the request url.
This change is not required response header consists of exec-time not the start time

2023-04-11 06:59 UTC, vanithavalluripalli9 approved these changes

2023-04-11 06:59 UTC, merged