issue-627 : remote protocol is now taken from configuration
openBackhaul/ApplicationPattern pull request #633
Opened 2023-03-31 12:37 UTC by DanaSunal

Fixes #627

2023-03-31 12:41 UTC, DanaSunal commented
Reviewer is @vanithavalluripalli9

2023-04-10 16:46 UTC, vanithavalluripalli9 requested changes

2023-04-10 16:46 UTC, vanithavalluripalli9 commented on server/applicationPattern/applicationPattern/onfModel/models/layerProtocols/OperationClientInterface.js
> +        return remoteProtocol + "//" + remoteAddress + ":" + remotePort;
remoteProtocol should be converted to lower case and the pattern should be remoteProtocol + "://"

2023-04-11 06:58 UTC, vanithavalluripalli9 approved these changes

2023-04-11 06:58 UTC, merged