upgrade fakeipscript
openBackhaul/ApplicationPattern pull request #642
Opened 2023-04-12 14:59 UTC by sunil-kumar-meena

below tasks covered
1. Separated fakeToOriginalIPMapping.json data based on client and server
2. Added protocol update support for client
3. Added Release Number update support for client

@vanithavalluripalli9 is a reviewer

2023-04-13 15:29 UTC, vanithavalluripalli9 commented
Reviewer is @PrathibaJee

2023-04-17 16:09 UTC, PrathibaJee requested changes

2023-04-17 16:09 UTC, PrathibaJee commented on server/FakeToOriginalIPConverter/FakeToOriginalIPConverter.js
> +            if (httpClientUuid != undefined) {
For the client , I could able to see that , we added a new attribute called “new-release”.
And the existing attribute “release” carries the details of the old-release.

You are trying to find the ltp instance for the old-release and then updating the 
- old-release to new release 
- old-ip-address, port , protocol to new

**For example ,** 
In the fakeIPAddress mapping file , lets say for the EATL application , the details are as below ,
old-release = 1.0.0 , new-release = 2.0.0 , ip-address = 1.1.1.1 , port = 3000 , protocol = https
In the load file , if EATL client is in the old-release 1.0.0 , then the new-release and tcp information shall be updated.
**Problem :**
But , what if ? the load file already consists of the new-release 2.0.0 ? 
Looks like the fake-ips will not be replaced for this instance.

**Can we modify the script as below ?**
**Assumption :**
fakeIPAddress mapping file always consists of the updated version that is running in the production.
That means , if live network consists of the version 33.0.0 , then only that information will be available in this file.
**change :**

```
Find the ltp instance based on the application-name and new-release number
    If instance found then 
    Update the tcp information 
Else 
    Find the ltp instance based on the application-name and old-release number
    If instance found then 
        Update the release information 
        Update the tcp information 
```

2023-05-26 11:12 UTC, PrathibaJee commented
Many thanks for the changes. But , as per the decision made in the issue ApplicationPattern/issues/247 , the changes in this PullRequests are not required. Hence , closing this PR.

2023-05-26 11:12 UTC, closed without merging