To extend the REST client to support query parameter
openBackhaul/ApplicationPattern pull request #879
Opened 2023-09-28 09:28 UTC by vanithavalluripalli9

Fixes #878

2023-09-28 14:50 UTC, PrathibaJee requested changes

2023-09-29 06:36 UTC, vanithavalluripalli9 commented on server/applicationPattern/applicationPattern/rest/client/RequestBuilder.js
> +const Qs =  require('qs');
Thank you for the comment . It is not required.

2023-09-29 06:36 UTC, vanithavalluripalli9 commented on server/applicationPattern/applicationPattern/rest/client/eventDispatcher.js
> +exports.dispatchEvent = function (operationClientUuid, httpRequestBody, user, xCorrelator, traceIndicator, customerJourney, isMethodGET=false, params) {
Thank you for the comment . Done

2023-09-29 09:25 UTC, PrathibaJee approved these changes
Thanks for fixing the review comments. Merging the PR.

2023-09-29 09:25 UTC, merged